open-component-model/ocm-controller

- Makefile
- api/v1alpha1/componentversion_types.go
- config/crd/bases/delivery.ocm.software_componentversions.yaml
- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
- examples/component.yaml
- pkg/ocm/ocm.go
> Renamed the name to componentName and fixed the generated empty yaml file

- api/v1alpha1/componentversion_types.go
- api/v1alpha1/configuration_types.go
- api/v1alpha1/localization_types.go
- api/v1alpha1/resource_types.go
- controllers/componentversion_controller.go
- controllers/configuration_controller.go
- controllers/resource_controller.go
Signed-off-by: Soule BA <bah.soule@gmail.com>
The idea is to have a discussion over this and create separate issues were needed.
> Add TODO comments based on code discovery

- .github/workflows/tests.yaml
- Makefile
Signed-off-by: Soule BA <bah.soule@gmail.com>
> adding a unit test github action

- pkg/oci/repository.go
Signed-off-by: Soule BA <bah.soule@gmail.com>
The [descriptor](https://pkg.go.dev/github.com/opencontainers/image-spec/specs-go/v1#Descriptor) contains the `digest` needed to fetch the blob.
> return a descriptor when pushing a blob

- docs/architecture.md
Add architecture document for OCM Kubernetes controller set (KCS).
> Add architecture doc

- controllers/componentversion_controller.go
- go.mod
- go.sum
- pkg/ocm/ocm.go
- pkg/ocm/setup_test.go
Component Descriptors are now signed using the `JsonNormalizationv2`  algorithm.
This PR ensures this option is set when performing signature verification.
It also contains a number of fixes:
- ensure authentication is performed when checking for new component versions
- don't exit the reconcile loop early if `expandReferences` is not set to true.
> Fix Verification

- .github/workflows/release.yaml
This fixes the var for the RC input to use a different format. Same fix as the one for the `ocm` repo, should have added it here too in my previous PR. Sorry. 😓
> Fix conditional for RC input

- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yaml
- config/default/kustomization.yaml
- config/default/labels.yaml
- config/default/namespace.yaml
Add the manifest and installation files to the release artifacts.
> feat(release): add manifests to release artifacts

- docs/release_notes/v0.3.0.md
- pkg/version/release.go
> release: v0.3.0

- .gitignore
- Tiltfile
- controllers/snapshot_controller.go
- controllers/snapshot_controller_test.go
- main.go
- pkg/cache/cache.go
- pkg/cache/fakes/cache.go
- pkg/oci/repository.go
- pkg/oci/repository_test.go
- pkg/oci/setup_test.go
- tilt-settings.yaml.example
The finalizer should delete any cached data that is assigned to the snaphost.
> feat: add finalizer to snapshots

- api/v1alpha1/componentdescriptor_types.go
- api/v1alpha1/componentversion_types.go
- api/v1alpha1/configuration_types.go
- api/v1alpha1/localization_types.go
- api/v1alpha1/resource_types.go
- api/v1alpha1/snapshot_types.go
- config/crd/bases/delivery.ocm.software_componentdescriptors.yaml
- config/crd/bases/delivery.ocm.software_componentversions.yaml
- config/crd/bases/delivery.ocm.software_configurations.yaml
- config/crd/bases/delivery.ocm.software_localizations.yaml
- config/crd/bases/delivery.ocm.software_resources.yaml
- config/crd/bases/delivery.ocm.software_snapshots.yaml
cv - ComponentVersion
cd - ComponentDescriptor
cl - Localitzation
cf - Configuration
cre - Resource
> feat: add shortName to all CRDs

- api/v1alpha1/componentversion_types.go
- config/crd/bases/delivery.ocm.software_componentversions.yaml
- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
> feat: allow rollback specifically

- controllers/mutation_reconcile_looper.go
- pkg/ocm/ocm.go
> fix: add check for nil component descriptor

- api/v1alpha1/mutation_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/delivery.ocm.software_configurations.yaml
- config/crd/bases/delivery.ocm.software_localizations.yaml
- controllers/mutation_generate_subst_rules.go
- controllers/mutation_reconcile_looper.go
- controllers/suite_test.go
- go.mod
I have to verify it with a proper manual test run as well. But this should do the trick of having the ability to completely change structures.
Closes #160
> chore(ref): use apiextensionv1.JSON instead of map[string]string

- .github/workflows/dispatch-e2e.yaml
Action to trigger e2e tests using event dispatching.
> add workflow to trigger e2e tests

- docs/release_notes/v0.7.0.md
- pkg/version/release.go
Update release notes for v0.7.0 release.
> feat: add release notes for v0.7.0

- docs/release_notes/v0.7.1.md
- pkg/version/release.go
> Prepare Release v0.7.1

- docs/release_notes/v0.8.0.md
- pkg/version/release.go
Add release notes and bump version to v0.8.0.
> release: v0.8.0

- controllers/configuration_controller.go
- controllers/fluxdeployer_controller.go
- controllers/localization_controller.go
- controllers/resource_controller.go
This fix ensures that we enqueue watched resources correctly.
> Fix Watched Resource Enqueuing

- docs/release_notes/v0.8.1.md
- pkg/version/release.go
Bump version and add release notes.
> release: v0.8.1

- controllers/snapshot_controller.go
- controllers/snapshot_controller_test.go
> fix: stuck snapshots

- api/v1alpha1/componentversion_types.go
- config/crd/bases/delivery.ocm.software_componentversions.yaml
- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
Closes https://github.com/open-component-model/ocm-controller/issues/170
> feat: remove rollback featuer

- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
fix leader election role name to be unique
> Fix role name

- docs/release_notes/v0.11.0.md
- pkg/version/release.go
> feat: add new release docs

- docs/release_notes/v0.14.1.md
- pkg/fakes/ocm.go
- pkg/version/release.go
> feat: add type to mock resource

- .github/workflows/e2e.yaml
> Change from field to text to avoid CR

- docs/api/v1alpha1/ocm.md
- hack/api-docs/config.json
This PR adds api docs for the `ResourcePipeline` custom resource.
open-component-model/ocm-website#106
> Add API docs for ResourcePipeline

- docs/release_notes/v0.16.0.md
- pkg/version/release.go
> release: prepare release for v0.16.0

- controllers/component_version_predicate.go
- controllers/componentversion_controller.go
- controllers/configuration_controller.go
- controllers/fluxdeployer_controller.go
- controllers/localization_controller.go
- controllers/resource_controller.go
- controllers/snapshot_controller.go
- pkg/status/mutate_condition_status.go
> feat: add mark as done and delete ReconcilingCondition

- docs/release_notes/v0.16.1.md
- pkg/version/release.go
> release: prepare release for v0.16.1

- README.md
- Related Issue https://github.com/open-component-model/ocm-controller/issues/235
> docs: update local testing guide

- .github/workflows/assign_issues_to_project.yaml
- .github/workflows/blackduck_scan_scheduled.yaml
- .github/workflows/mend_scan.yaml
> feat: add automation for created issues in this repository

- .github/workflows/assign_issues_to_project.yaml
> fix: missing private key for token generator

- .github/workflows/assign_issues_to_project.yaml
> fix: organization and repository name

- .github/workflows/assign_issues_to_project.yaml
> fix: name of repo and org

- .github/workflows/caretaker_slash_commands.yaml
- .github/workflows/flip_back_issue.yaml
> feat: add some more project automation actions

- .github/workflows/caretaker_slash_commands.yaml
> fix: use the latest version for caretaker

- README.md
- Related Issue #363 
-- https://github.com/open-component-model/ocm-controller/issues/363
- Closes #363  (issue)
- Fixes #363  (issue)
> docs(fix): Update README.md fixing issues/363

- controllers/componentversion_controller.go
- controllers/resource_controller.go
- Related Issue #368 (issue)
- Closes #368 (issue)
- Fixes #368 (issue)
> fix(logs): string replacement of "Applied version"

- docs/release_notes/v0.19.0.md
- pkg/version/release.go
> release: add docs for v0.19.0

- README.md
- config/samples/componentversion.yaml
- controllers/componentversion_contoller_test.go
- examples/basic/cv.yaml
- examples/mapping-with-cue/monolith_component_version.yaml
- examples/mapping-with-cue/src/component.yaml
- examples/resource-pipeline/componentfile.yaml
- examples/resource-pipeline/cv.yaml
- pkg/oci/repository_test.go
- pkg/ocm/ocm_test.go
- tilt-settings.yaml.example
Related Issue: https://github.com/open-component-model/ocm-project/issues/43
> chore: remove personal information

- metadata.yaml
add metadata for Hyperspace Portal
> add metadata for hyperspace

- README.md
Relates to https://github.com/open-component-model/ocm-project/issues/169
Not going too much into detail on individual operations but rather focus on explaining existing objects.
> doc: update the documentation to be more thorough

- docs/release_notes/v0.20.0.md
- pkg/version/release.go
> release: add release docs for 0.20.0

- docs/release_notes/v0.20.1.md
- pkg/version/release.go
> release: docs for v0.20.1

- docs/architecture.md
Fixes https://github.com/open-component-model/ocm-project/issues/169
> fix: update the architecture documentation

- config/default/kustomization.yaml
- docs/release_notes/v0.20.1.md
- docs/release_notes/v0.20.2.md
- pkg/version/release.go
Related to https://github.com/open-component-model/ocm-project/issues/181
> fix: add the right version in the image overlay for the deployment

- controllers/mutation_reconcile_looper.go
Closes https://github.com/open-component-model/ocm-project/issues/70.
> fix: remove predictable name in adjustments template

- docs/architecture.md
> fix: correct spelling for source and add missing kind

- docs/architecture.md
> fix: source for the localization is a ComponentVersion and not Resource

- config/default/kustomization.yaml
- docs/release_notes/v0.21.1.md
- pkg/version/release.go
> fix: update the controller version in install config

- docs/architecture.md
> remove http scheme from comp name

- config/default/kustomization.yaml
- docs/release_notes/v0.21.2.md
- pkg/version/release.go
> docs: add release notes for v0.21.2

- controllers/componentversion_controller.go
- controllers/fluxdeployer_controller.go
- controllers/resource_controller.go
- controllers/snapshot_controller.go
- pkg/event/event.go
- pkg/event/event_test.go
- pkg/status/mutate_condition_status.go
- pkg/status/register_status_defer.go
> fix: message formatting not passed in

- config/default/kustomization.yaml
- docs/release_notes/v0.21.3.md
- pkg/version/release.go
> docs: add release notes for v0.21.3

- config/default/kustomization.yaml
- docs/release_notes/v0.21.4.md
- pkg/version/release.go
> docs: add release notes for v0.21.4

- pkg/fakes/ocm.go
- pkg/ocm/ocm_test.go
> test: extended resource test with a more complex nested component

- api/v1alpha1/constants.go
- controllers/resource_controller.go
- controllers/resource_controller_test.go
- pkg/ocm/ocm.go
- pkg/ocm/ocm_test.go
Fix https://github.com/open-component-model/ocm-controller/issues/446
> feat: add reference path to the identity

- config/default/kustomization.yaml
- docs/release_notes/v0.21.5.md
- pkg/version/release.go
> docs: release notes for v0.21.5

- docs/release_notes/v0.22.0.md
- pkg/version/release.go
> docs: release notes for v0.22.0

- .github/workflows/release.yaml
- docs/release_notes/v0.22.1.md
- pkg/version/release.go
> fix: where the release version is coming from

- go.mod
> fix: fix module file require incorrect k8s client

- docs/release_notes/v0.23.0.md
- pkg/version/release.go
> docs: added release notes for v0.23.0

- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
> feat: add labels from component version to component descriptor

- docs/release_notes/v0.23.1.md
- pkg/version/release.go
> docs: added release notes for v0.23.1

- Tiltfile
> fix: allow duplicates true

- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
> fix: label value should be parsed correctly

- docs/release_notes/v0.23.3.md
- pkg/version/release.go
> docs: added release notes for v0.23.3

- .github/workflows/components.yaml
- .gitignore
- .golangci.yaml
- Dockerfile
- component/Dockerfile
- component/Makefile
- component/README.md
- component/helm_resource.yaml
- component/metadata.yaml
- component/resources.yaml
- component/sources.yaml
- go.mod
Fixes https://github.com/open-component-model/ocm-project/issues/197
> feat: add ocm component to the controller

- .github/workflows/components.yaml
- component/README.md
> fix: updated the readme and the component location

- .github/workflows/components.yaml
- component/Makefile
> fix: install ocm before running the ctf action

- docs/release_notes/v0.23.4.md
- pkg/version/release.go
> docs: add release docs

- docs/release_notes/v0.23.5.md
- pkg/version/release.go
> docs: release notes for v0.23.5

- docs/release_notes/v0.23.6.md
- pkg/version/release.go
> docs: release notes for v0.23.6

- controllers/configuration_strat_merge_patch.go
- controllers/mutation_reconcile_looper.go
> fix: tar up the workdir instead of just the output folder

- docs/release_notes/v0.23.7.md
- pkg/version/release.go
> docs: release notes for v0.23.7

- controllers/configuration_controller_test.go
Fixes https://github.com/open-component-model/ocm-controller/issues/440
> ref: simplify the navigation inside the test cases for conf/loc

- api/v1alpha1/condition_types.go
- api/v1alpha1/fluxdeployer_types.go
- controllers/fluxdeployer_controller.go
- controllers/fluxdeployer_controller_test.go
- deploy/crds/delivery.ocm.software_fluxdeployers.yaml
Fixes https://github.com/open-component-model/ocm-project/issues/217
> feat: add wait for all created resources to flux deployer

- docs/release_notes/v0.23.8.md
- pkg/version/release.go
> docs: release notes for v0.23.8

- controllers/fluxdeployer_controller.go
- controllers/fluxdeployer_controller_test.go
> fix: incorrectly adding nil objects to the check list

- docs/release_notes/v0.23.9.md
- pkg/version/release.go
> docs: release docs for v0.23.9

- api/v1alpha1/componentversion_types.go
- api/v1alpha1/condition_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
- controllers/mutation_reconcile_looper.go
- controllers/resourcepipeline_controller.go
- deploy/crds/delivery.ocm.software_componentversions.yaml
- deploy/templates/deployment_manager.yaml
- pkg/ocm/fakes/fakes.go
- pkg/ocm/ocm.go
- pkg/ocm/ocm_test.go
Fixes https://github.com/open-component-model/ocm-project/issues/220
> feat: add subscription to the ComponentVersion

- docs/release_notes/v0.24.0.md
- pkg/version/release.go
> docs: release docs for v0.24.0

- README.md
Update Readme on how to use Helm charts.
> doc: update on how to use helm charts

- api/v1alpha1/componentversion_types.go
- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
- controllers/mutation_reconcile_looper.go
- controllers/resource_controller.go
- controllers/resourcepipeline_controller.go
- controllers/suite_test.go
- pkg/ocm/ocm.go
- pkg/ocm/ocm_test.go
Fix https://github.com/open-component-model/ocm-project/issues/226
> fix: empty repository url while reconciling

- docs/release_notes/v0.24.1.md
- pkg/version/release.go
> docs: release docs for v0.24.1

- docs/release_notes/v0.24.2.md
- pkg/version/release.go
> docs: release docs for v0.24.2

- component/Dockerfile
- component/Makefile
- component/resources.yaml
Fixes https://github.com/open-component-model/ocm-project/issues/264
> fix: the creation of the component

- docs/release_notes/v0.24.3.md
- pkg/version/release.go
> release: docs for v0.24.3

- .github/workflows/release.yaml
- Makefile
> feat: add missing pushing components on release

- pkg/version/release.go
> release: docs for v0.24.4

- docs/release_notes/v0.24.5.md
- pkg/version/release.go
> release: docs for v0.24.5

- Makefile
- docs/release_notes/v0.24.6.md
- pkg/version/release.go
> fix: adding missing make target

- .github/workflows/components_push.yaml
- .github/workflows/components_test.yaml
- .github/workflows/release.yaml
- Makefile
- docs/release_notes/v0.24.7.md
- pkg/version/release.go
> fix: folder does not exist

- .github/workflows/components_push.yaml
- docs/release_notes/v0.24.8.md
- pkg/version/release.go
> fix: missing authentication

- .github/workflows/components_push.yaml
- docs/release_notes/v0.24.9.md
- pkg/version/release.go
> fix: add environment property token

- .github/workflows/components_push.yaml
- .github/workflows/release.yaml
- docs/release_notes/v0.24.11.md
> fix: adding a token parameter to the workflow call

- Makefile
- component/Makefile
- docs/release_notes/v0.24.13.md
- pkg/version/release.go
> fix: missing ocm setup

- .github/workflows/release.yaml
- docs/release_notes/v0.25.1.md
- pkg/version/release.go
> fix: add namespace to the install yaml generator command

- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
- pkg/ocm/ocm_test.go
Closes https://github.com/open-component-model/ocm-project/issues/314
@dee0sap This should pretty much do what you want, I will also test this manually.
> fix: enable rolling back versions to older versions

- docs/release_notes/v0.25.2.md
- pkg/version/release.go
> docs: release v0.25.2

- .github/CODEOWNERS
- .github/dependabot.yml
- .github/release-drafter.yml
- .github/settings.yml
Let's have centrally managed labels on https://github.com/open-component-model/.github
> chore(labels): centrally managed

- .github/workflows/code-scan.yml
see: https://github.com/open-component-model/ocm-project/issues/270
fixes: https://github.com/open-component-model/ocm-controller/issues/583
> chore: Gosec - enable security linting

- .github/workflows/codeql.yml
> chore: correct typo

- .github/workflows/e2e.yaml
- .github/workflows/tests.yaml
On-behalf-of: Gerald Morrison (SAP) <gerald.morrison@sap.com>
Signed-off-by: Gerald Morrison (SAP) <gerald.morrison@sap.com>
correct exclude paths
> chore: update workflow paths to exclude workflow files from triggers

- .github/workflows/check-manifest-generation-diff.yaml
- .github/workflows/e2e.yaml
- .github/workflows/tests.yaml
- docs/release_notes/v0.26.0.md
- pkg/version/release.go
Add release nodes and switch to large runner to avoid action failures.
> chore: prepare release for version v0.26.0

- docs/release_notes/v0.26.0.md
> chore: prepare releases notes

- e2e/same_resource_test.go
> fix: update the used repository name

- e2e/create_test_component.go
- e2e/main_test.go
> chore: refactoring the signing test to make it more robust

- deploy/templates/deployment_manager.yaml
- deploy/templates/deployment_registry.yaml
- deploy/values.yaml
Address issue [502](https://github.com/open-component-model/ocm-project/issues/502)
[502](https://github.com/open-component-model/ocm-project/issues/502)
> Registry Deployment template now gets image info from values.yaml

- deploy/values.yaml
Address issue [505](https://github.com/open-component-model/ocm-project/issues/505) 
https://github.com/open-component-model/ocm-project/issues/505
> Move to version 3 of registry, addressing SAP compliance concerns.

- docs/release_notes/v0.26.1.md
- pkg/version/release.go
> chore: release for v0.26.1

- docs/release_notes/v0.26.2.md
- pkg/version/release.go
> chore: release notes for v0.26.2

- docs/release_notes/v0.26.6.md
- pkg/version/release.go
> chore: release docs for v0.26.6

- docs/release_notes/v0.26.7.md
- pkg/version/release.go
> chore: release docs for v0.26.7
