open-component-model/ocm-controller

- .github/workflows/ghcr.yaml
This PR ensures that the registry server image is also published when we ship the ocm-controller image.
> Publish OCM registry server image to ghcr.io

- .github/workflows/ghcr.yaml
- Makefile
- config/default/patches/init-container.yaml
Due to an issue with the ghcr we are unable push an image to `open-component-model/ocm-registry-server`. To sidestep this and unblock users we are changing the name of the container repository to `open-component-model/ocm-registry`.
> Change Registry Image Name

- Makefile
The deploy and dev-deploy make commands set the kustomization image for the registry server. These are now updated to use the correct registry server, missed in the last PR.
> Update makefile with new registry image name

- go.mod
- go.sum
- pkg/ocm/ocm.go
- pkg/ocm/setup_test.go
The problem was that ocm-contoller was using an OCM version from 2022 December. However, this also means that the changes made in OCM weren't backward compatible regarding signing. We have to keep an eye out for that.
The second part is that we were setting the signing algorithm to V2 in the code. This will fail if the signing on the outside is set to V1 or not set, as it defaults to V1. Perhaps we should expose this setting in the CRD.
> Fix verification process

- controllers/configuration_controller.go
- controllers/localization_controller.go
This PR fixes the localization and configuration indexer so that they don't panic when the source is a `resourceRef`.
> Fix Localization indexer

- .github/workflows/tests.yaml
This PR adds a `workflow_call` for the `tests.yaml` workflow so that it can be called from the release workflow :)
> Add workflow_call to test GA workflow

- .goreleaser.yaml
The variable `{ .Arch }` is not available for the `dockers` field, only for building the binary. Instead, `{ runtime.Goarch }` is available everywhere. Tested this with the goreleaser CLI and it went through.
> Change goreleaser runtime variable for docker

- api/v1alpha1/componentversion_types.go
- config/crd/bases/delivery.ocm.software_componentversions.yaml
It's technically already optional anyways, since it's a slice that is allowed to be empty.
> ref: make verify an optional field

- api/v1alpha1/mutation_types.go
- config/crd/bases/delivery.ocm.software_configurations.yaml
- config/crd/bases/delivery.ocm.software_localizations.yaml
- controllers/configuration_controller.go
- controllers/configuration_controller_test.go
- controllers/localization_controller.go
- controllers/localization_controller_test.go
- controllers/suite_test.go
- pkg/cache/fakes/cache.go
- pkg/ocm/setup_test.go
Extend `shouldReconcile` for `Configuration` and `Localization` to include checking the source Snapshot and Configuration object for changes.
> feat: add source and configuration snapshot check to shouldReconcile

- Tiltfile
- tilt-settings.yaml.example
- rebuild the container and use an internal registry without having to fiddle with kustomize
- hot reload the container ( this builds the container atm, process swapping is a future feature )
- create secrets
- bootstraps or installs flux
- hot swap for manager process ( no need to rebuild the entire image )
- install unpacked
> feat: add tiltfile

- config/rbac/role.yaml
- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
- controllers/configuration_controller.go
- controllers/configuration_controller_test.go
- controllers/localization_controller.go
- controllers/localization_controller_test.go
- controllers/resource_controller.go
- controllers/resource_controller_test.go
- controllers/snapshot_controller.go
- controllers/snapshot_controller_test.go
- go.mod
- go.sum
- main.go
- pkg/event/event.go
- pkg/event/event_test.go
Closes #49 
This PR:
* Initialises the event recorder for the ocm-controller in `main.go` and for all reconcilers
* Adds RBAC to ClusterRole to create/patch events for all reconcilers of ocm-controller.
* Adds an `event()` method that emits an event, for example, when reconciliation succeeds or fails, with unit tests
* Adds events to Snapshot, Resource, Localization, and Configuration reconcilers
Reconciliation that finished successfully or is requeued, similar to the Flux one:
```
ocm-system   18s         Normal    Succeeded                    componentversion/podinfo               Reconciliation finished, next run in 10m0s
```
Reconciliation with an error:
```
ocm-system    6m3s        Warning   CheckVersionFailedReason   componentversion/podinfo                        Version …
```
> Add events to `ocm-controller`

- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
- go.mod
- pkg/ocm/fakes/fakes.go
- pkg/ocm/ocm.go
- pkg/ocm/ocm_test.go
- you can't define a concrete version to install if the latest version is greater than the version you choose, because we always return the latest
- you can't define a constraint that would still work if the constraint it something like `<=2.0.0` but the latest version is above that like `3.0.0`. It should reconcile `2.0.0` but it will actually error saying, no versions met the constraint
- you can't downgrade. if you change your constraint to `<=2.0.0` from `>2.0.0` nothing will happen
Reconcile versions up-to the given constraint. This means that if a constraint is provided, we will return whatever the maximum is that STILL VALIDATES to that constraint. This is achieved by looping through the descending order of versions and returning the first that validates.
Downgrading or pinning to …
> bug: fix version checking up to constraint

- .gitignore
- Tiltfile
- config/manager/deployment.yaml
- config/rbac/service_account.yaml
We no longer require the registry credentials secret to be passed in to
the controller at startup. That means we can remove the reference from
the Service Account, Pod Template and Tiltfile.
> Remove references to `regcred` secret

- controllers/mutation_reconcile_looper.go
Fix a nil pointer that occurred when trying to fetch an non-existent artifact.
> Bugfix: nil pointer if artifact is missing

- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
This is a small refactor to help ensure the component version reconciler doesn't
enter a stalled state when the version check fails. One common scenario
where the version check may fail is if the component version has not
been pushed to a repository. The controller should handle this
gracefully and continue to check until such time as the version is
available.
> refactor: cv reconciler

- controllers/componentversion_contoller_test.go
- controllers/componentversion_controller.go
Condition on the ComponentVersion is never set to Ready in case there is another reconciling like a version update or upon a requeue. This pr https://github.com/open-component-model/ocm-controller/pull/207 started to surface that issue. Another test that surfaced it was when I was trying to update the values for MPAS. It never updated it because the ComponentVersion went into Reconiling state and NotReady which made the loop wait, and eventually time out with:
```
2023-06-06T14:48:47Z	ERROR	Reconciliation did not succeed, retrying in 10m0s	{"name": "podinfocomponent-version", "namespace": "mpas-sample-project", "reconciler kind": "ComponentVersion", "annotations": {}, "error": "ProgressingWithRetry"}
github.com/fluxcd/pkg/runtime/events.(*Recorder).AnnotatedEventf …
```
> restrored the reconciling condition

- e2e/create_test_component.go
- e2e/helpers.go
- e2e/main_test.go
Cleanup summary:
- removed the getComponent function as now with the simple component for signing it wasn't needed
- moved the testcases at the top of the file for easy finding
- removed all the waits and used a common checkCondition function for all objects
- added two missing err checks
> chore(ref): cleanup the end to end tests

- pkg/snapshot/snapshot_writer.go
In issue #68 I described trying to make this flow 
ComponentVersion -> Localization -> Configuration -> FluxDeployer
, where the helm chart is a resource with in the componentversion, work without success.
One of the problems is that the tag generated by the Configuration snapshot is not a valid semvar.   So even if you use the extraIdentity helmChart=<chart name> to make it so the snapshot repo will be named in a way helm will accept, see [here](https://github.com/open-component-model/ocm-controller/blob/f56a4d62a17064b390cd1ce81eb0151de02fba46/pkg/ocm/ocm.go#L558), helm still will complain cause tag is just the k8s revision of the object owning the snapshot.
At the moment I am just tacking on ".0.0" to keep helm from complaining when the extraidentity helmChart=<chart name> is present. …
> fix: Quick hack to address issue 68 - snapshot tag doesn't meet strict semver check

- api/v1alpha1/reference_types.go
- api/v1alpha1/resource_types.go
- config/crd/bases/delivery.ocm.software_configurations.yaml
- config/crd/bases/delivery.ocm.software_fluxdeployers.yaml
- config/crd/bases/delivery.ocm.software_localizations.yaml
- config/crd/bases/delivery.ocm.software_resourcepipelines.yaml
- config/crd/bases/delivery.ocm.software_resources.yaml
- controllers/mutation_reconcile_looper.go
- controllers/resource_controller.go
- controllers/resourcepipeline_controller.go
Closes https://github.com/open-component-model/ocm-project/issues/66
> fix: resourceRef should be a required property

- README.md
- controllers/resource_controller.go
> doc: add some more information regarding versioning

- controllers/componentversion_controller.go
- controllers/configuration_controller.go
- controllers/localization_controller.go
- controllers/resource_controller.go
- controllers/snapshot_controller.go
- pkg/status/register_status_defer.go
Fix https://github.com/open-component-model/ocm-controller/issues/436
> fix: only update failed progress in case of error

- README.md
> Update helm chart version

- Makefile
- hack/prime_test_cluster.sh
* the deploy targets do not work anymore since the directory-structure does not exist. This is because the deployment needs an additionaly OCI registry.
To deploy the controller one can use the instructions in the README.md
* add context on how to run `make test`
* cleanup
> Sidequest: Remove technical debt

- e2e/main_test.go
- pkg/ocm/fakes/fakes.go
- pkg/ocm/ocm.go
- pkg/ocm/ocm_test.go
Fixes https://github.com/open-component-model/ocm-project/issues/336
> fix: return the last verified version that fits the constraint

- docs/release_notes/v0.25.4.md
- pkg/version/release.go
> docs: add release docs for v0.25.4

- .github/workflows/check-manifest-generation-diff.yaml
- api/v1alpha1/constants.go
- pkg/oci/repository.go
change exception for gosec linter
> chore: change exception for gosec linter

- api/v1alpha1/constants.go
- pkg/oci/repository.go
test new format #nosec [RuleList] [-- Justification]
> test new format #nosec [RuleList] [-- Justification]

- .github/workflows/blackduck_scan.yaml
> change trigger

- .github/workflows/blackduck_scan.yaml
Enhance the Blackduck scan workflow by ignoring workflow paths, improving status checking, and adjusting the cronjob schedule. Remove excluded directories from the scan to streamline the process.
> chore: Update Blackduck scan workflow and cronjob timing

- .github/workflows/e2e.yaml
The slack GHA is failing since some time because the API changed. This change fixes the problem
> update slack GHA

- .github/workflows/components.yaml
- component/Makefile
> adjust GHA to trigger on PR and not pull_request_target

- pkg/ocm/ocm.go
- pkg/ocm/ocm_test.go
Fixes https://github.com/open-component-model/ocm-controller/issues/629
> fix: use the current component version for the default resource version

- docs/release_notes/v0.26.3.md
- pkg/version/release.go
> chore: release notes and version update for v0.26.3

- controllers/resource_controller.go
- controllers/resource_controller_test.go
> fix: adjust the resource controller to use the descriptor version for defaulting instead of the component version

- deploy/templates/deployment_registry.yaml
Fixes the indentation to the registry deployment resource block when Helm template is overwritten with specific resource limitations.
Fixes [issue 581](https://github.com/open-component-model/ocm-project/issues/581)
> fix indentation for registry deployment resource block

- deploy/templates/deployment_registry.yaml
There are lot of error logging and noise in the registry deployment due to TLS errors on the probes
- changing the Liveness and Readiness probes `httpGet` on `/v2` path to avoid TLS handshake errors
Additionally there are noises from OTEL metrics (enabled by default in registry) but they can be overridden with env via values
```yaml
- name: OTEL_TRACES_EXPORTER
value: none
```
This is a very small fix and may not fit into v2 controllers but until then it would be nice to get this fix in.
> fix(registry): change readiness and liveness probe to httpGet /v2

- main.go
Fixes https://github.com/open-component-model/ocm-project/issues/684
> fix: manually set client-side ratelimiting to previous values

- docs/release_notes/v0.26.9.md
- pkg/version/release.go
> chore: release notes and version bump for v0.26.9
